version: '3'

services:
  frontend:
    image: davegdd/app_frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./storage:/storage

  backend:
    image: davegdd/app_backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage
